rgbdtum:
  - rgbd_dataset_freiburg1_xyz
  - rgbd_dataset_freiburg2_xyz
  - rgbd_dataset_freiburg1_floor
  - rgbd_dataset_freiburg1_desk
  - rgbd_dataset_freiburg1_desk2
  - rgbd_dataset_freiburg2_desk
  - rgbd_dataset_freiburg3_long_office_household
  - rgbd_dataset_freiburg3_nostructure_texture_near_withloop
  - rgbd_dataset_freiburg3_structure_texture_far
  - rgbd_dataset_freiburg3_structure_texture_near
  - rgbd_dataset_freiburg2_desk_with_person
  - rgbd_dataset_freiburg3_sitting_xyz
  - rgbd_dataset_freiburg3_walking_halfsphere
  - rgbd_dataset_freiburg1_plant

  - rgbd_dataset_freiburg3_cabinet_validation
  - rgbd_dataset_freiburg3_long_office_household_validation
  - rgbd_dataset_freiburg3_nostructure_texture_near_withloop_validation
  - rgbd_dataset_freiburg3_structure_notexture_far_validation
  - rgbd_dataset_freiburg3_structure_notexture_near_validation
  - rgbd_dataset_freiburg3_structure_texture_far_validation
  - rgbd_dataset_freiburg3_sitting_static_validation
  - rgbd_dataset_freiburg3_sitting_xyz_validation
  - rgbd_dataset_freiburg3_walking_static_validation
  
# replica:
#   - office0

# eth:
# - 'table_3'
# 7scenes:
# - 'chess_seq-01'
# euroc:
# - 'V1_01_easy'
# kitti:
# - '04'