rgbdtum:
  - rgbd_dataset_freiburg2_pioneer_slam
  - rgbd_dataset_freiburg3_nostructure_notexture_far
  - rgbd_dataset_freiburg3_structure_notexture_far
  - rgbd_dataset_freiburg3_structure_notexture_near
  - rgbd_dataset_freiburg3_sitting_static
  - rgbd_dataset_freiburg3_walking_static
  - rgbd_dataset_freiburg1_teddy
  - rgbd_dataset_freiburg2_coke
  - rgbd_dataset_freiburg2_dishes
  - rgbd_dataset_freiburg2_flowerbouquet
  - rgbd_dataset_freiburg2_flowerbouquet_brownbackground
  - rgbd_dataset_freiburg2_metallic_sphere
  - rgbd_dataset_freiburg2_metallic_sphere2
  - rgbd_dataset_freiburg3_cabinet
  - rgbd_dataset_freiburg3_teddy


  # - rgbd_dataset_freiburg3_large_cabinet_validation
  # - rgbd_dataset_freiburg3_nostructure_notexture_far_validation
  # - rgbd_dataset_freiburg3_nostructure_notexture_near_withloop_validation
  # - rgbd_dataset_freiburg3_nostructure_texture_far_validation
  # - rgbd_dataset_freiburg3_structure_texture_near_validation
  # - rgbd_dataset_freiburg3_sitting_halfsphere_validation
  # - rgbd_dataset_freiburg3_sitting_rpy_validation
  # - rgbd_dataset_freiburg3_walking_halfsphere_validation

# replica:
#   - 'office0'
# nuim:
#   - 'living_room_traj0_frei_png'
# scannetplusplus:
#   - '56a0ec536c'
# rgbdtum:
#   - 'rgbd_dataset_freiburg3_structure_notexture_far'
# tartanair:
#   - 'ME001'
