rgbdtum:
  - rgbd_dataset_freiburg1_rpy
  - rgbd_dataset_freiburg2_rpy
  - rgbd_dataset_freiburg1_room
  - rgbd_dataset_freiburg2_360_hemisphere
  - rgbd_dataset_freiburg3_nostructure_texture_far
  - rgbd_dataset_freiburg3_sitting_rpy
  - rgbd_dataset_freiburg3_walking_xyz
  - rgbd_dataset_freiburg3_walking_rpy
  - rgbd_dataset_freiburg3_large_cabinet 
  - rgbd_dataset_freiburg3_walking_xyz_validation
  - rgbd_dataset_freiburg3_walking_rpy_validation

# eth:
# - 'large_loop_1'
# hilti2022:
# - 'exp04_construction_upper_level'

# euroc:
#  - 'MH_04_difficult'

# rgbdtum:
# # - 'rgbd_dataset_freiburg3_structure_notexture_far'
# - 'rgbd_dataset_freiburg3_nostructure_notexture_far'
# - 'rgbd_dataset_freiburg3_walking_xyz'
# #- 'rgbd_dataset_freiburg3_nostructure_texture_near_withloop'