#openloris:
#   - cafe1-1
  # - cafe1-2
  #- market1-1
  # - market1-2
  # - market1-3
# tartanair:
#   - 'ME001'

# madmax:
#   - A-0

#hilti2022:
  #- exp04_construction_upper_level
  #- exp05_construction_upper_level_2
  #- exp06_construction_upper_level_3
#  - exp14_basement_2
  #- exp16_attic_to_upper_gallery_2
  #- exp18_corridor_lower_gallery_2
#antarctica:
  #- 'DJI_202401111904_001'
  #- 'DJI_202401111932_002'
  #- 'DJI_202401111932_003'
 # - 'DJI_202401112014_004'

#yandiwanba:
  #- 'test1'
#  - 'test4'
#lizardisland:
#  - 'LIRS_FEB1'
#replica:
#  - 'office0'
#  - 'office1'
#  - 'office2'
#  - 'office3'
#  - 'office4'
#  - 'room0'
#  - 'room1'
#  - 'room2'
rgbdtum:
  - 'rgbd_dataset_freiburg3_structure_texture_far'
  #- 'rgbd_dataset_freiburg1_xyz'
  - 'rgbd_dataset_freiburg3_long_office_household'

# eth:
#   - 'table_3'
#kitti:
#  - '04'
#euroc:
#  - 'MH_01_easy'
#  - 'MH_02_easy'
#  - 'MH_03_medium'
#  - 'MH_04_difficult'
#  - 'MH_05_difficult'
#  - 'V1_01_easy'
#  - 'V1_02_medium'
#  - 'V1_03_difficult'
#  - 'V2_01_easy'
#  - 'V2_02_medium'
#  - 'V2_03_difficult'
#monotum:
#  - 'sequence_01'
#tartanair
#  - 'ME001'
#7scenes
#  - 'redkitchen_seq-01'
#  - 'heads_seq-01'