eth3d_mvs_dslr:
  - 'courtyard_dslr'
  - 'delivery_area_dslr'
  - 'electro_dslr'
  - 'facade_dslr'
  - 'kicker_dslr'
  - 'meadow_dslr'
  - 'office_dslr'
  - 'pipes_dslr'
  - 'playground_dslr'
  - 'relief_dslr'
  - 'relief_2_dslr'
  - 'terrace_dslr'
  - 'terrains_dslr'