nuim:
  - 'living_room_traj0_frei_png'
  - 'living_room_traj1_frei_png'
  - 'living_room_traj2_frei_png'
  - 'living_room_traj3_frei_png'
  - 'traj0_frei_png'
  - 'traj1_frei_png'
  - 'traj2_frei_png'
  - 'traj3_frei_png'