# exp_test_graph:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1}
#   Module: orbslam2

# exp_test_rgbdtum_droidslam:
#   Config: config_easy.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: droidslam

# exp_test_rgbdtum_orbslam2:
#   Config: config_easy.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: orbslam2

# exp_test_rgbdtum_mast3rslam:
#   Config: config_easy.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: mast3rslam

exp_test_rgbdtum_dpvo:
  Config: config_rgbdtum.yaml
  NumRuns: 10
  Parameters: {verbose: 0}
  Module: dpvo

# exp_config_easy_det_orbslam2:
#   Config: config_easy.yaml
#   NumRuns: 100
#   Parameters: {verbose: 0, rgb_idx: [0,999]}
#   Module: orbslam2

# exp_config_weird_droidslam:
#   Config: config_weird.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_idx: [0,999]}
#   Module: droidslam

# exp_config_easy_dpvo:
#   Config: config_easy.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: dpvo

# exp_config_easy_orbslam2:
#   Config: config_easy.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0}
#   Module: orbslam2


# exp_glomap_squidle_test_0_499:
#   Config: config_squidle.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_idx: [0, 499], matcher_type: exhaustive}
#   Module: glomap

# exp_glomap_squidle_test_400_999:
#   Config: config_squidle.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_idx: [400, 999], matcher_type: exhaustive}
#   Module: glomap

# exp_glomap_squidle_test_900_1499:
#   Config: config_squidle.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_idx: [900, 1499], matcher_type: exhaustive}
#   Module: glomap

# exp_glomap_squidle_test_1400_1999:
#   Config: config_squidle.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_idx: [1400, 1999], matcher_type: exhaustive}
#   Module: glomap

# exp_glomap_squidle_test_1900_2499:
#   Config: config_squidle.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_idx: [1900, 2499], matcher_type: exhaustive}
#   Module: glomap

# exp_glomap_squidle_test_2400_3010:
#   Config: config_squidle.yaml
#   NumRuns: 1
#   Parameters: {verbose: 0, rgb_idx: [2400, 3010], matcher_type: exhaustive}
#   Module: glomap

# exp_dpvo_antarctica:
#   Config: config_debug.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, matcher_type: exhaustive, max_rgb: 1000000}
#   Module: glomap

# exp_glomap_scannetplusplus:
#   Config: config_scannetplusplus.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, max_rgb: 50}
#   Module: glomap

# exp_dpvo_nuim:
#   Config: config_nuim.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: dpvo

# exp_droidslam_nuim:
#   Config: config_nuim.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: droidslam

# exp_dpvo_rgbdtum:
#   Config: config_rgbdtum.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: dpvo

# exp_droidslam_rgbdtum:
#   Config: config_rgbdtum.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: droidslam

# exp_glomap_rgbdtum:
#   Config: config_rgbdtum.yaml
#   NumRuns: 1
#   Parameters: {verbose: 1, max_rgb: 50}
#   Module: glomap

# exp_orbslam2_rgbdtum:
#   Config: config_rgbdtum.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: orbslam2


# exp_glomap_eth:
#   Config: config_eth.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: glomap

# exp_orbslam2_eth:
#   Config: config_eth.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: orbslam2

# exp_dpvo_eth:
#   Config: config_eth.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: dpvo

# exp_droidslam_eth:
#   Config: config_eth.yaml
#   NumRuns: 10
#   Parameters: {verbose: 0}
#   Module: droidslam

#exp_depth_orbslam2_invz_gtdepth_ablation:
#  Config: config_debug.yaml
#  NumRuns: 200
#  Parameters: {verbose: 0, mode: rgbd}
#  Ablation: /home/fontan/ablation.csv
#  Module: orbslam2
#
#exp_depth_orbslam2_invz_depthpro_ablation:
#  Config: config_debug.yaml
#  NumRuns: 200
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_pro.txt}
#  Ablation: /home/fontan/ablation.csv
#  Module: orbslam2

#exp_depth_orbslam2_gtdepth_ablation:
#  Config: config_debug.yaml
#  NumRuns: 200
#  Parameters: {verbose: 0, mode: rgbd}
#  Ablation: /home/fontan/ablation.csv
#  Module: orbslam2
#
#exp_depth_orbslam2_depthpro_ablation:
#  Config: config_debug.yaml
#  NumRuns: 200
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_pro.txt}
#  Ablation: /home/fontan/ablation.csv
#  Module: orbslam2

#exp_ablation_glomap:
#  Config: config_debug.yaml
#  NumRuns: 2
#  Parameters: {verbose: 1, max_rgb: 50}
#  Module: glomap


#exp_depth_orbslam2_gtdepth:
#  Config: config_debug.yaml
#  NumRuns: 25
#  Parameters: {verbose: 0, mode: rgbd}
#  Module: orbslam2
#
#exp_depth_orbslam2_mono:
#  Config: config_debug.yaml
#  NumRuns: 25
#  Parameters: {verbose: 0, mode: mono}
#  Module: orbslam2
#
#exp_depth_orbslam2_depthpro:
#  Config: config_debug.yaml
#  NumRuns: 25
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_pro.txt}
#  Module: orbslam2

#exp_antarctica:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1}
#  Module: droidslam

#exp_antarctica_dust3r:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1, rgb_txt: rgb_20.txt, 'max_rgb': 10}
#  Module: dust3r

#exp_antarctica_orbslam2:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1}
#  Module: orbslam2

#exp_antarctica_monogs:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1}
#  Module: monogs

#exp_antarctica_glomap:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1, rgb_txt: rgb_66.txt}
#  Module: glomap

#exp_depthpro:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1}
#  Module: depthpro

#exp_depth_orbslam2_mono:
#  Config: config_debug.yaml
#  NumRuns: 30
#  Parameters: {verbose: 0, mode: mono}
#  Module: orbslam2
#
#exp_depth_orbslam2_gtdepth:
#  Config: config_debug.yaml
#  NumRuns: 30
#  Parameters: {verbose: 0, mode: rgbd}
#  Module: orbslam2
#
#exp_depth_orbslam2_depthpro:
#  Config: config_debug.yaml
#  NumRuns: 30
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_pro.txt}
#  Module: orbslam2
##
#exp_depth_orbslam2_depthpro_anchored:
#  Config: config_debug.yaml
#  NumRuns: 30
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_pro_anchored.txt }
#  Module: orbslam2

#exp_yandiwamba:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1, max_rgb: 50}
#  Module: glomap

#exp_yandiwamba:
#  Config: config_debug.yaml
#  NumRuns: 51278
#  Parameters: {verbose: 1}
#  Module: monogs

#exp_depthpro:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1}
#  Module: depthpro

#monogs_lizard:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1, rgb_txt: rgb.txt}
#  Module: monogs

#exp_depth_monogs:
#  Config: config_debug.yaml
#  NumRuns: 3
#  Parameters: {verbose: 0, mode: rgbd, max_rgb: 50000}
#  Module: monogs
#
#exp_depth_anything_monogs:
#  Config: config_debug.yaml
#  NumRuns: 3
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_anything_v2.txt}
#  Module: monogs
#
#exp_mono_monogs:
#  Config: config_debug.yaml
#  NumRuns: 3
#  Parameters: {verbose: 0, mode: mono}
#  Module: monogs

#exp_depth_droidslam_gtdepth:
#  Config: config_debug.yaml
#  NumRuns: 25
#  Parameters: {verbose: 0, mode: rgbd}
#  Module: droidslam
#
#exp_depth_droidslam_depthanything:
#  Config: config_debug.yaml
#  NumRuns: 25
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_anything_v2.txt}
#  Module: droidslam
#
#exp_depth_droidslam_depthpro:
#  Config: config_debug.yaml
#  NumRuns: 25
#  Parameters: {verbose: 0, mode: rgbd, rgb_txt: rgbd_depth_pro.txt}
#  Module: droidslam

#exp_depth_droidslam_depthpro_anchored:
#  Config: config_debug.yaml
#  NumRuns: 1
#  Parameters: {verbose: 1, mode: rgbd, rgb_txt: rgbd_depth_pro_anchored.txt}
#  Module: droidslam

#
#exp_depth_droidslam_mono:
#  Config: config_debug.yaml
#  NumRuns: 25
#  Parameters: {verbose: 0, mode: mono}
#  Module: droidslam

#exp_depth_orbslam2:
#  Config: config_debug.yaml
#  NumRuns: 3
#  Parameters: {verbose: 1, vocabulary: Vocabulary/ORBvoc.txt, mode: rgbd}
#  Module: orbslam2
#
#exp_depth_anything_orbslam2:
#  Config: config_debug.yaml
#  NumRuns: 3
#  Parameters: {verbose: 1, vocabulary: Vocabulary/ORBvoc.txt, mode: rgbd, rgb_txt: rgbd_depth_anything_v2.txt}
#  Module: orbslam2
#
#exp_mono_orbslam2:
#  Config: config_debug.yaml
#  NumRuns: 3
#  Parameters: {verbose: 1, vocabulary: Vocabulary/ORBvoc.txt, mode: mono}
#  Module: orbslam2

#droidslam_noise:
#  Config: config_debug.yaml
#  NumRuns: 2000
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.filter_thresh],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#droidslam_nominal:
#  Config: config_debug.yaml
#  NumRuns: 5
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.beta],
#               image_noise: 5,
#               max_rgb: 500}
#  Module: droidslam

#droidslam_50frames_beta:
#  Config: config_debug.yaml
#  NumRuns: 1807
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.beta],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#droidslam_50frames_keyframe_thresh:
#  Config: config_debug.yaml
#  NumRuns: 500
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.keyframe_thresh],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#droidslam_50frames_frontend_thresh:
#  Config: config_debug.yaml
#  NumRuns: 500
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.frontend_thresh],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#droidslam_50frames_frontend_radius:
#  Config: config_debug.yaml
#  NumRuns: 500
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.frontend_radius],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#droidslam_50frames_filter_thresh:
#  Config: config_debug.yaml
#  NumRuns: 500
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.filter_thresh],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#droidslam_50frames_backend_thresh:
#  Config: config_debug.yaml
#  NumRuns: 500
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.backend_thresh],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#droidslam_50frames_backend_radius:
#  Config: config_debug.yaml
#  NumRuns: 500
#  Parameters: {verbose: 0, upsample: 0,
#               ablation_param: [settings.backend_radius],
#               image_noise: 1,
#               max_rgb: 50}
#  Module: droidslam

#glomap_50frames_noise: ???????????
#  Config: config_debug.yaml
#  NumRuns: 2000
#  Parameters: {verbose: 0,
#               max_rgb: 50}
#  Module: glomap

#glomap_50frames_nominal:
#  Config: config_debug.yaml
#  NumRuns: 2
#  Parameters: {verbose: 0,
#               max_rgb: 50}
#  Module: glomap

#glomap_50frames_Thresholds_max_reprojection_error:
#  Config: config_debug.yaml
#  NumRuns: 2000
#  Parameters: {verbose: 0,
#               max_rgb: 50,
#               image_noise: 1,
#               ablation_param: [Thresholds.max_reprojection_error]}
#  Module: glomap
#
#glomap_50frames_BundleAdjustment_thres_loss_function:
#  Config: config_debug.yaml
#  NumRuns: 2000
#  Parameters: {verbose: 0,
#               max_rgb: 50,
#               image_noise: 1,
#               ablation_param: [BundleAdjustment.thres_loss_function]}
#  Module: glomap
#
#glomap_50frames_TwoViewGeometry_max_error:
#  Config: config_debug.yaml
#  NumRuns: 2000
#  Parameters: {verbose: 0,
#               max_rgb: 50,
#               image_noise: 1,
#               ablation_param: [matcher.TwoViewGeometry_max_error]}
#  Module: glomap
#
#glomap_50frames_SiftExtraction_peak_threshold:
#  Config: config_debug.yaml
#  NumRuns: 2000
#  Parameters: {verbose: 0,
#               max_rgb: 50,
#               image_noise: 1,
#               ablation_param: [feature_extractor.SiftExtraction_peak_threshold]}
#  Module: glomap
#
#glomap_50frames_SiftMatching_max_ratio:
#  Config: config_debug.yaml
#  NumRuns: 2000
#  Parameters: {verbose: 0,
#               max_rgb: 50,
#               image_noise: 1,
#               ablation_param: [matcher.SiftMatching_max_ratio]}
#  Module: glomap