exp_config_extreme_mast3rslam:
  Config: config_extreme.yaml
  NumRuns: 1
  Parameters: {verbose: 0, rgb_idx: [0,999]}
  Module: mast3rslam

exp_config_extreme_droidslam:
  Config: config_extreme.yaml
  NumRuns: 1
  Parameters: {verbose: 0, rgb_idx: [0,999]}
  Module: droidslam