exp_config_easy_mast3rslam:
  Config: config_easy.yaml
  NumRuns: 5
  Parameters: {verbose: 1}
  Module: mast3rslam

exp_config_easy_droidslam:
  Config: config_easy.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: droidslam

exp_config_easy_dpvo:
  Config: config_easy.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: dpvo

exp_config_easy_orbslam2:
  Config: config_easy.yaml
  NumRuns: 5
  Parameters: {verbose: 0}
  Module: orbslam2