exp_config_difficult_mast3rslam:
  Config: config_difficult.yaml
  NumRuns: 1
  Parameters: {verbose: 0, rgb_idx: [0,999]}
  Module: mast3rslam

exp_config_difficult_droidslam:
  Config: config_difficult.yaml
  NumRuns: 1
  Parameters: {verbose: 0, rgb_idx: [0,999]}
  Module: droidslam

# exp_config_difficult_dpvo:
#   Config: config_difficult.yaml
#   NumRuns: 5
#   Parameters: {verbose: 0}
#   Module: dpvo

# exp_config_difficult_orbslam2:
#   Config: config_difficult.yaml
#   NumRuns: 5
#   Parameters: {verbose: 0}
#   Module: orbslam2
