eiffel:
  # - eff15
  # - eff16
  # - eff18
  # - eff20
  # - eff1516
  # - eff1618
  # - eff1820
  # - effall
  # - eff15-s01
  # - eff16-s01
  # - eff18-s01
  # - eff20-s01
  # - effall-s01
  # - eff15-s02
  # - eff16-s02
  # - eff18-s02
  # - effthree-s02
  - effthree-s10
